### ISSUE TITLE
Some installation issues

### ISSUE THREAD

**Issue by ellimondo** [JayGeorge/jaygeorge_perch_admin_style#2]
Hi Jay

Thanks so much for your work on this app - it is SOOOOOOO much better than standard Perch UI ;)

I've installed as a submodule and have had a few issues getting it working without errors. I hope you don't mind me leaving my report here – never done this type of thing before so excuse the noob speak!

- If the folder /apps/plugins/ui is empty then Perch completely fails to load with a load of unable to load header errors. Once **custom-admin.css** and **favicon.ico** (could this just be png or ignored if not there?) are added then the CP loads fine. Maybe this need adding to the instructions?

- There is an error on loading the admin page from the sidebar. 

`Notice: ob_flush(): failed to flush buffer. No buffer to flush in READACTED/perch/core/inc/sidebar_start.php on line 2`

- There is an SQL table missing post install which may be contributing to the issue above.

`Invalid query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wib_perchrw.perch3_jaygeorge_perch_admin_style_settings' doesn't exist`

Thanks again.

Jon

**Comment by ellimondo** [comment]
Forget the missing ui bits - I just found the instructions in the app itself.

**Comment by ellimondo** [comment]
Hi Jay,

Here's a screengrab for you:

![admin style app](https://user-images.githubusercontent.com/697383/46886367-9d824300-ce52-11e8-9813-b70aaede4e15.png)

**Comment by ellimondo** [comment]
Hello!

Updating to PHP 7.2.1 has got rid of the ob_flush warning. Was on 7.1.12. 

SQL warning still remains.

**Comment by jaygeorge** [comment]
I believe this is fixed now.
