### ISSUE TITLE
Language txt are not ignored

### ISSUE THREAD

**Issue by cognetif** [JayGeorge/jaygeorge_perch_admin_style#6]
Perch is kindof annoying in that it doesn't centralize translation files but they're spread out here and there including in modules, so if you modify translations the module will have /lang/<local>.txt file added for each locale you have in the system.

if we don't have : 

```
lang/*.txt
```

within the `.gitignore` of a module project, those files will get added and updated by the core system and mess up updating of the module.

**Comment by jaygeorge** [comment]
Not sure what you're suggesting—do you want me to update the gitignore? If you make a pull request I'll merge it.

**Comment by cognetif** [comment]
@JayGeorge - There you go, pull request created.
